name: 2dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ffmpeg
  - pillow
  - pip
  - python=3.9
  - pytorch
  - torchaudio
  - torchvision
  - typing_extensions
  - pip:
    - open3d==0.18.0
    - mediapy
    - lpips
    - scikit-image
    - tqdm
    - trimesh
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn
    - plyfile
    - opencv-python
